# Default values for dongtai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# dongtai config
# appNamespace: dongtai-iast
skipMysql: false 
skipRedis: false
accessType: ClusterIP 
imageVersion: latest

mysql:
  host: dongtai-mysql
  port: 3306
  name: dongtai_webapi
  user: root
  password: dongtai-iast

redis:
  host: dongtai-redis
  port: 6379
  password: 123456
  db: 0

enginUrl: http://dongtai-engine-svc:80

apiServer: http://dongtai-openapi-svc:80

csrfTrustOrigins: .example.com

smtp:
  server: smtp_server
  user: smtp_user
  password: smtp_password
  from_addr: from_addr
  ssl: False
  cc_addr: cc_addr

aliyun_oss:
  access_key: LTAI5t7pu9WUT2DcbknfNiaD
  access_key_secret: ZoEOSi7KfayQ7JalvJVHa37fdZ4XFY
