blank_issues_enabled: false
contact_links:
  - name: ğŸ› Bug report
    url: https://github.com/HXSecurity/DongTai/issues/new?assignees=exexute&labels=bug&projects=HXSecurity/DongTai/1&template=bug_report.yaml
    about: Report a bug to help us improve DongTai

  - name: ğŸš€ Feature request
    url: https://github.com/HXSecurity/DongTai/issues/new?assignees=exexute&labels=feature&projects=HXSecurity/DongTai/1&template=feature_request.yaml
    about: Suggest an idea for DongTai

  - name: â“ Ask a question
    url: https://github.com/HXSecurity/DongTai/discussions/new?category=q-a
    about: Ask and discuss questions with other DongTai community members

  - name: ğŸ“š Documentation
    url: https://hxsecurity.github.io/DongTaiDoc
    about: Check the documentation for help
