blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question
    url: https://github.com/HXSecurity/DongTai/discussions/new?category=q-a
    about: Ask and discuss questions with other DongTai community members

  - name: ğŸ“š Documentation
    url: https://hxsecurity.github.io/DongTaiDoc
    about: Check the documentation for help
  - name: "\U0001F440 Agent compatibility issues report"
    url: https://github.com/HXSecurity/DongTai-agent-java/issues/new?labels=compatibility&projects=1&template=agent_compatibility.yaml
    about: Report a Agent compatibility issues to help us improve DongTai agent compatibility. 
