---
# dongtai-server服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-server
  namespace: iast-test
  annotations:
    kubesphere.io/description: dongtai-server
  labels:
    app: dongtai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-server
  template:
    metadata:
      labels:
        app: dongtai-server
    spec:
      containers:
        - name: dongtai-server-container
          image: registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-test:VERSION
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /opt/dongtai/dongtai_conf/conf/config.ini
              subPath: config.ini
          env:
            - name: DONGTAI_CONCURRENCY
              value: --processes 2 --stats :3031 --stats-http
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
      volumes:
        - name: configfile
          configMap:
            name: dongtai-iast-config.ini
      imagePullSecrets:
        - name: aliyun-registry-secret
---
# dongtai-server服务
apiVersion: v1
kind: Service
metadata:
  name: dongtai-server-svc
  namespace: iast-test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: dongtai-server
  type: ClusterIP
---
#dongtai-worker-task服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-worker-task
  namespace: iast-test
  annotations:
    kubesphere.io/description: dongtai-worker-task
  labels:
    app: dongtai-worker-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-worker-task
  template:
    metadata:
      labels:
        app: dongtai-worker-task
    spec:
      containers:
        - name: dongtai-worker-task-container
          image: registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-test:VERSION
          command: [ "/bin/bash","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "beat" ]
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /opt/dongtai/dongtai_conf/conf/config.ini
              subPath: config.ini
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
      volumes:
        - name: configfile
          configMap:
            name: dongtai-iast-config.ini
      imagePullSecrets:
        - name: aliyun-registry-secret
---

# dongtai-worker-high-freq服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-worker-high-freq
  namespace: iast-test
  annotations:
    kubesphere.io/description: dongtai-worker-high-freq
  labels:
    app: dongtai-worker-high-freq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-worker-high-freq
  template:
    metadata:
      labels:
        app: dongtai-worker-high-freq
    spec:
      containers:
        - name: dongtai-worker-high-freq-container
          image: registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-test:VERSION
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-high-freq" ]
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /opt/dongtai/dongtai_conf/conf/config.ini
              subPath: config.ini
          env:
            - name: DONGTAI_CONCURRENCY
              value: -P gevent --concurrency=121
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
      volumes:
        - name: configfile
          configMap:
            name: dongtai-iast-config.ini
      imagePullSecrets:
        - name: aliyun-registry-secret
---
# dongtai-worker-beat服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-worker-beat
  namespace: iast-test
  annotations:
    kubesphere.io/description: dongtai-worker-beat
  labels:
    app: dongtai-worker-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-worker-beat
  template:
    metadata:
      labels:
        app: dongtai-worker-beat
    spec:
      containers:
        - name: dongtai-worker-beat-container
          image: registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-test:VERSION
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-beat" ]
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /opt/dongtai/dongtai_conf/conf/config.ini
              subPath: config.ini
          env:
            - name: DONGTAI_CONCURRENCY
              value: --concurrency=2
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
      volumes:
        - name: configfile
          configMap:
            name: dongtai-iast-config.ini
      imagePullSecrets:
        - name: aliyun-registry-secret
---
# dongtai-worker-other服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-worker-other
  namespace: iast-test
  annotations:
    kubesphere.io/description: dongtai-worker-other
  labels:
    app: dongtai-worker-other
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-worker-other
  template:
    metadata:
      labels:
        app: dongtai-worker-other
    spec:
      containers:
        - name: dongtai-worker-other-container
          image: registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-test:VERSION
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-other" ]
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /opt/dongtai/dongtai_conf/conf/config.ini
              subPath: config.ini
          env:
            - name: DONGTAI_CONCURRENCY
              value: --concurrency=2
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
      volumes:
        - name: configfile
          configMap:
            name: dongtai-iast-config.ini
      imagePullSecrets:
        - name: aliyun-registry-secret
---
# dongtai-worker-sca服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-worker-sca
  namespace: iast-test
  annotations:
    kubesphere.io/description: dongtai-worker-sca
  labels:
    app: dongtai-worker-sca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-worker-sca
  template:
    metadata:
      labels:
        app: dongtai-worker-sca
    spec:
      containers:
        - name: dongtai-worker-sca-container
          image: registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-test:VERSION
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-sca" ]
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /opt/dongtai/dongtai_conf/conf/config.ini
              subPath: config.ini
          env:
            - name: DONGTAI_CONCURRENCY
              value: --concurrency=2
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
      volumes:
        - name: configfile
          configMap:
            name: dongtai-iast-config.ini
      imagePullSecrets:
        - name: aliyun-registry-secret
---
# dongtai-worker-es服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-worker-es
  namespace: iast-test
  annotations:
    kubesphere.io/description: dongtai-worker-es
  labels:
    app: dongtai-worker-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-worker-es
  template:
    metadata:
      labels:
        app: dongtai-worker-es
    spec:
      containers:
        - name: dongtai-worker-es-container
          image: registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-test:VERSION
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-es" ]
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /opt/dongtai/dongtai_conf/conf/config.ini
              subPath: config.ini
          env:
            - name: DONGTAI_CONCURRENCY
              value: --concurrency=2
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
      volumes:
        - name: configfile
          configMap:
            name: dongtai-iast-config.ini
      imagePullSecrets:
        - name: aliyun-registry-secret
