{{- define "config.ini" -}}
[mysql]
host = {{.Values.mysql.host}}
port = {{.Values.mysql.port}}
name = {{.Values.mysql.name}}
user = {{.Values.mysql.user}}
password = {{.Values.mysql.password}}

[redis]
host = {{.Values.redis.host}}
port = {{.Values.redis.port}}
password = {{.Values.redis.password}}
db = {{.Values.redis.db}}

[engine]
url = {{.Values.enginUrl}}

[apiserver]
url = {{.Values.apiServer}}

[security]
csrf_trust_origins = {{.Values.csrfTrustOrigins}}


[smtp]
server = {{.Values.smtp.server}}
user = {{.Values.smtp.user}}
password = {{.Values.smtp.password}}
from_addr = {{.Values.smtp.from_addr}}
ssl = {{.Values.smtp.ssl}}
cc_addr = {{.Values.smtp.cc_addr}}
port = {{.Values.smtp.port}}


[aliyun_oss]
access_key = {{.Values.aliyun_oss.access_key}}
access_key_secret = {{.Values.aliyun_oss.access_key_secret}}

{{- end -}}


apiVersion: v1
kind: Secret
metadata:
  name: dongtai-iast-config.ini
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    config.ini: |-
        {{ include "config.ini" . | b64enc }}