{{- if .Values.max }}
---
# dongtai-worker-chain服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-chain
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-chain
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-chain
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-chain
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-chain
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-chain-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-chain" ]
          env:
            - name: DONGTAI_CONCURRENCY
              value: --concurrency=12
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}
{{- end }}